### PR TITLE
Zihao/disheslayout

### PR DESCRIPTION
**Pull request by ltroin**
layout screen for restaurant detail

### CODE REVIEW

**Review by anhanh11001 — CHANGES_REQUESTED** [review]
A few problems

1. When you scroll, the header pictures and title should be pushed up so that the menu items can be shown in full screen. Right now, this is only scrolling in half of the screen. The space is taken unnecessarily

https://user-images.githubusercontent.com/36192582/157020205-a3c4e07f-7308-4d92-8bbf-cf6c10ad312e.mov

2. The dialog shouldn't have a back button to be removed. That's not a recommended/common design. Also, when user clicks outside the dialog, the dialog should be removed.

https://user-images.githubusercontent.com/36192582/157020766-53b6f83f-b564-415b-8dd5-f787c26de1f1.mov

3. Selecting items behavior is being weird here: When I click on 300G options, it is showing and clicking multiple ones. Is it intended?



https://user-images.githubusercontent.com/36192582/157020856-f663c363-b7de-4e6d-adfd-d8ce6c50c46e.mov

**Comment by ltroin** [comment]
> 

1. I will look into the implementation of it.
2. the problem is that when user touches add or remove button, it's really easily to accidentally close the modal, a bit weird.
3. they are intended, some dummy data, I would like to see how it looks like when browsing.

**Comment by anhanh11001** [comment]
> 2. the problem is that when user touches add or remove button, it's really easily to accidentally close the modal, a bit weird.

no it's not, the button is big enough, it's also the common design pattern. For example, in the material design from Google here: https://material.io/components/dialogs#simple-dialog , we have this behavior
Screenshot 2022-03-07 at 13 26 48

> they are intended, some dummy data, I would like to see how it looks like when browsing.

Then that's weird that when clicking on 300g, multiple options selected. Can you fix it?

**Comment by anhanh11001** [comment]
Btw, the button size and the add/remove selector is a bit large also

**Pull request merged**
